
export enum ElemTypeEnum {
  INPUT_TEXT = 'input-text',
  BUTTON = 'button',
  LABEL = 'label',
  AVATAR = 'avatar',
  TEXTAREA = 'textarea',
  PASSWORD = 'password',
  SWITCH = 'switch',
  CHECKBOX = 'checkbox',
  VIDEO = 'video',
  IMAGE = 'img',
  FILE = 'file',
  OUT_TEXT = 'out-text',
  ICON_BUTTON = 'icon-button',
  LINK = 'link',
  CARD = 'card',
  TABLE = 'table',
  DATA_GRID = 'datagrid',
  CALENDER = 'calendar',
  DROPDOWN_LIST = 'dropdown-list',
  STEPPER = 'stepper',
  RADIO_BUTTON = 'radio-button',
}
